"""Add completed to models

Revision ID: 0512f873d49e
Revises: 01cb8203d4bd
Create Date: 2024-10-04 13:30:12.607150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0512f873d49e'
down_revision: Union[str, None] = '01cb8203d4bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('completed', sa.Boolean(), nullable=True))
    
    # Обновляем данные в существующих записях
    op.execute("UPDATE tasks SET completed = False WHERE completed IS NULL")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'completed')
    # ### end Alembic commands ###
