"""add Enum for priority

Revision ID: faa2dee9d7fd
Revises: 0512f873d49e
Create Date: 2024-10-04 19:11:48.846966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faa2dee9d7fd'
down_revision: Union[str, None] = '0512f873d49e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Обновляем данные в существующих записях
    op.execute("UPDATE tasks SET priority = 'low' WHERE priority = 'string'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
